# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=24)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lang', models.CharField(choices=[('fr', 'French'), ('en', 'English'), ('de', 'German'), ('it', 'Italian'), ('es', 'Spanish'), ('ja', 'Japanese')], default='fr', max_length=2)),
                ('fullname', models.CharField(max_length=64)),
                ('firstname', models.CharField(blank=True, max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity',
                'managed': False,
                'verbose_name': 'Localized Identitity',
                'verbose_name_plural': 'Localized Identities',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lang', models.CharField(choices=[('fr', 'French'), ('en', 'English'), ('de', 'German'), ('it', 'Italian'), ('es', 'Spanish'), ('ja', 'Japanese')], default='fr', max_length=2)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=64)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'info',
                'managed': False,
                'verbose_name': 'Localized Info',
                'verbose_name_plural': 'Localized Infos',
            },
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inscription', models.CharField(blank=True, max_length=64)),
                ('fullname', models.CharField(max_length=64)),
                ('firstname', models.CharField(blank=True, max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('birth', models.IntegerField()),
                ('death', models.IntegerField()),
                ('rank', models.SmallIntegerField()),
                ('cenotaph', models.BooleanField()),
                ('picture', models.CharField(blank=True, max_length=128)),
                ('enabled', models.BooleanField()),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personality',
                'managed': False,
                'verbose_name': 'Personality',
                'verbose_name_plural': 'Personalities',
            },
        ),
        migrations.CreateModel(
            name='PersonalityCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'personality_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sepulture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('geog', models.TextField(blank=True, null=True)),
                ('section', models.SmallIntegerField()),
                ('urn', models.CharField(max_length=8)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sepulture',
                'managed': True,
            },
        ),
    ]
